front_left_1:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 3
front_left_2:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 3
front_left_3:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 3
front_right_1:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 3
front_right_2:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 3
front_right_3:
  ID: 6
  Return_Delay_Time: 0
  Operating_Mode: 3
rear_left_1:
  ID: 7
  Return_Delay_Time: 0
  Operating_Mode: 3
rear_left_2:
  ID: 8
  Return_Delay_Time: 0
  Operating_Mode: 3
rear_left_3:
  ID: 9
  Return_Delay_Time: 0
  Operating_Mode: 3
rear_right_1:
  ID: 10
  Return_Delay_Time: 0
  Operating_Mode: 3
rear_right_2:
  ID: 11
  Return_Delay_Time: 0
  Operating_Mode: 3
rear_right_3:
  ID: 12
  Return_Delay_Time: 0
  Operating_Mode: 3